site_name: DNNBrain
nav:
    - Get Started: 'install.md'
    - Tutorials: 'tutorials/idx.md'
    - Examples: 'examples/idx.md'
    - Docs: 'docs/idx.md'
    - Cite DNNBrain: 'cite.md'
theme: mkdocs
markdown_extensions:
    - toc:
        permalink: "#"
        separator: "_"
