site_name: DNNBrain
nav:
    - Get Started: 'install.md'
    - Tutorials: 'tutorials/index.md'
    - Examples: 'examples/index.md'
    - Docs: 'docs/index.md'
    - Cite DNNBrain: 'cite.md'
theme: mkdocs
markdown_extensions:
    - toc:
        permalink: "#"
        separator: "_"
