site_name: DNNBrain
nav:
    - Installation: 'install.md'
    - Usage notes:
        - File format: 'usage/file_format.md'
        - Command-line arguments:
            - dnn_act: 'usage/cmd/dnn_act.md'
        - Using python lib:
            - extract_dnn_activation: 'usage/pylib/extract_dnn_activation.md'
    - API: 'API/TBD.md'
    - Citing DNNBrain: 'citing.md'
theme: readthedocs
markdown_extensions:
    - toc:
        permalink: "#"
        separator: "_"